[package]
name = "linked_list"
version = "0.1.0"
edition = "2021"

[dependencies]
riscv-rt = "0.13.0"
panic-halt = "0.2.0"
embedded-alloc = "0.6.0"
riscv = { version = "0.12.1", features = ["critical-section-single-hart"] }
riscv-semihosting = "0.1.2"
